import { useState, useMemo } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { Download, Zap, Play, Save } from 'lucide-react';
import TopBar from '../components/TopBar';
import { useApp } from '../context/AppContext';
import { computeStats, formatCurrency } from '../utils/analytics';

const PRESET_REPORTS = [
  { id:'monthly', label:'Monthly Travel Summary', icon:'📅', desc:'Spend trends, trip counts and category breakdown by month' },
  { id:'compliance', label:'Policy Compliance Scorecard', icon:'✅', desc:'Compliance rates, violations and policy adherence trends' },
  { id:'savings', label:'Savings Opportunity Report', icon:'💰', desc:'Ranked savings opportunities with $ estimates and effort ratings' },
  { id:'risk', label:'Risk & Fraud Flag Report', icon:'🚨', desc:'All fraud flags, duplicate detections and anomaly analysis' },
  { id:'executive', label:'AI Executive Summary', icon:'🤖', desc:'AI-generated narrative summary of your travel programme' },
  { id:'credits', label:'Unused Credits & Expiry', icon:'🎫', desc:'All ticket credits with expiry dates and urgency scoring' },
  { id:'vendor', label:'Vendor Performance Report', icon:'🏢', desc:'Spend by vendor with contract compliance and savings potential' },
];

const DIMENSIONS = ['Department','Traveler','Route','Vendor','Cost Centre','Booking Class'];
const METRICS = ['Total Spend','Trip Count','Avg Cost','Compliance %','Savings Found'];
const CHART_TYPES = ['Bar Chart','Line Chart','Pie Chart','Table'];

function ReportContent({ reportId, stats }: { reportId:string; stats:ReturnType<typeof computeStats> }) {
  if (reportId==='monthly') return (
    <div style={{ display:'flex', flexDirection:'column', gap:16 }}>
      <h3 style={{ fontSize:14, fontWeight:700 }}>Monthly Travel Summary</h3>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:12 }}>
        {[{label:'Total Spend',value:formatCurrency(stats.totalSpend)},{label:'Total Trips',value:stats.totalTrips},{label:'Avg Per Trip',value:formatCurrency(stats.avgCostPerTrip)}].map((s,i) => (<div key={i} style={{ background:'#F5F4FF', borderRadius:10, padding:'14px', textAlign:'center' }}><div style={{ fontSize:10, color:'#94A3B8', fontWeight:600, textTransform:'uppercase' }}>{s.label}</div><div style={{ fontSize:22, fontWeight:800, color:'#7C3AED', marginTop:4 }}>{s.value}</div></div>))}
      </div>
      <ResponsiveContainer width="100%" height={220}><BarChart data={stats.monthlyTrend}><CartesianGrid strokeDasharray="3 3" stroke="#F1F0FF"/><XAxis dataKey="month" tick={{ fontSize:11 }}/><YAxis tickFormatter={v=>`$${(v/1000).toFixed(0)}K`} tick={{ fontSize:11 }}/><Tooltip formatter={(v:any) => formatCurrency(v)}/><Bar dataKey="spend" fill="#7C3AED" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>
    </div>
  );
  if (reportId==='executive') return (
    <div style={{ display:'flex', flexDirection:'column', gap:16 }}>
      <h3 style={{ fontSize:14, fontWeight:700 }}>AI Executive Summary</h3>
      <div style={{ background:'linear-gradient(135deg,#1a0533,#3b0764)', borderRadius:12, padding:'24px' }}>
        <div style={{ fontSize:12, color:'rgba(255,255,255,0.5)', marginBottom:12 }}>Generated by Traivio AI · {new Date().toLocaleDateString()}</div>
        <p style={{ color:'rgba(255,255,255,0.9)', fontSize:14, lineHeight:1.8 }}>Your organisation's travel programme shows total annual spend of <strong style={{ color:'#C084FC' }}>{formatCurrency(stats.totalSpend)}</strong> across {stats.totalTrips} trips, averaging <strong style={{ color:'#C084FC' }}>{formatCurrency(stats.avgCostPerTrip)}</strong> per trip. Compliance stands at <strong style={{ color:stats.complianceRate>=85?'#34D399':'#FBBF24' }}>{stats.complianceRate}%</strong>, with {stats.policyViolations} policy violations representing cost exposure.</p>
        <p style={{ color:'rgba(255,255,255,0.75)', fontSize:13, lineHeight:1.8, marginTop:12 }}>AI analysis has identified <strong style={{ color:'#34D399' }}>{formatCurrency(stats.savingsFound)}</strong> in actionable savings. Immediate priorities: (1) Resolve {stats.fraudFlags} fraud flags, (2) Redeem {formatCurrency(stats.unusedCreditsValue)} in expiring credits, (3) Implement advance booking enforcement.</p>
      </div>
    </div>
  );
  return (
    <div style={{ display:'flex', flexDirection:'column', gap:16 }}>
      <h3 style={{ fontSize:14, fontWeight:700 }}>{PRESET_REPORTS.find(r=>r.id===reportId)?.label}</h3>
      <ResponsiveContainer width="100%" height={220}><BarChart data={stats.spendByDepartment}><CartesianGrid strokeDasharray="3 3" stroke="#F1F0FF"/><XAxis dataKey="name" tick={{ fontSize:11 }}/><YAxis tickFormatter={v=>`$${(v/1000).toFixed(0)}K`} tick={{ fontSize:11 }}/><Tooltip formatter={(v:any) => formatCurrency(v)}/><Bar dataKey="value" radius={[4,4,0,0]}>{stats.spendByDepartment.map((e,i) => <Cell key={i} fill={e.color}/>)}</Bar></BarChart></ResponsiveContainer>
    </div>
  );
}

export default function Reports() {
  const { records } = useApp();
  const stats = useMemo(() => computeStats(records), [records]);
  const [activeReport, setActiveReport] = useState('monthly');
  const [tab, setTab] = useState<'presets'|'pivot'|'query'>('presets');
  const [pivot, setPivot] = useState({ dimension:'Department', metric:'Total Spend', chartType:'Bar Chart', dateRange:'Last 12 months', name:'' });
  const [savedTemplates, setSavedTemplates] = useState<typeof pivot[]>([]);
  const [nlQuery, setNlQuery] = useState('');
  const pivotData = useMemo(() => {
    if (pivot.dimension==='Department') return stats.spendByDepartment.map(d => ({ name:d.name, value:d.value }));
    if (pivot.dimension==='Traveler') { const map: Record<string,number>={}; records.forEach(r => { map[r.travelerName]=(map[r.travelerName]||0)+r.totalCost; }); return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,value]) => ({ name, value:Math.round(value) })); }
    return stats.spendByCategory.map(c => ({ name:c.name, value:c.value }));
  }, [pivot.dimension, records, stats]);
  const colors = ['#7C3AED','#0EA5E9','#10B981','#F59E0B','#EF4444','#8B5CF6'];
  return (
    <div style={{ minHeight:'100vh', background:'#F5F4FF' }}>
      <TopBar title="Reports & Analytics" subtitle="Preset reports, pivot builder and AI query" />
      <div style={{ padding:'24px 28px', display:'flex', flexDirection:'column', gap:20 }}>
        <div style={{ display:'flex', gap:2, background:'white', borderRadius:10, padding:4, border:'1px solid #EDE9FE', width:'fit-content' }}>
          {(['presets','pivot','query'] as const).map(t => (<button key={t} onClick={() => setTab(t)} style={{ padding:'7px 18px', borderRadius:8, border:'none', background:tab===t?'#7C3AED':'transparent', color:tab===t?'white':'#64748B', fontSize:13, fontWeight:tab===t?600:400, cursor:'pointer' }}>{t==='presets'?'Preset Reports':t==='pivot'?'Pivot Builder':'Natural Language'}</button>))}
        </div>
        {tab==='presets' && (
          <div style={{ display:'grid', gridTemplateColumns:'280px 1fr', gap:20 }}>
            <div style={{ display:'flex', flexDirection:'column', gap:8 }}>
              {PRESET_REPORTS.map(r => (<button key={r.id} onClick={() => setActiveReport(r.id)} style={{ display:'flex', alignItems:'flex-start', gap:10, padding:'12px 14px', borderRadius:10, background:activeReport===r.id?'#7C3AED':'white', color:activeReport===r.id?'white':'#475569', cursor:'pointer', textAlign:'left' as const, border:`1px solid ${activeReport===r.id?'#7C3AED':'#EDE9FE'}` }}><span style={{ fontSize:16, flexShrink:0 }}>{r.icon}</span><div><div style={{ fontSize:13, fontWeight:600 }}>{r.label}</div><div style={{ fontSize:11, opacity:0.7, marginTop:2, lineHeight:1.4 }}>{r.desc}</div></div></button>))}
            </div>
            <div className="card" style={{ padding:'24px' }}>
              <div style={{ display:'flex', justifyContent:'flex-end', gap:8, marginBottom:20 }}>
                <button style={{ display:'flex', alignItems:'center', gap:6, padding:'7px 14px', borderRadius:8, background:'#ECFDF5', border:'1px solid #A7F3D0', fontSize:13, color:'#065F46', fontWeight:500, cursor:'pointer' }}><Zap size={13}/> Run AI Summary</button>
                <button style={{ display:'flex', alignItems:'center', gap:6, padding:'7px 14px', borderRadius:8, background:'#F5F4FF', border:'1px solid #EDE9FE', fontSize:13, color:'#64748B', fontWeight:500, cursor:'pointer' }}><Download size={13}/> Export PDF</button>
              </div>
              <ReportContent reportId={activeReport} stats={stats}/>
            </div>
          </div>
        )}
        {tab==='pivot' && (
          <div style={{ display:'flex', flexDirection:'column', gap:16 }}>
            <div className="card" style={{ padding:'20px' }}>
              <h3 style={{ fontSize:14, fontWeight:700, marginBottom:16, color:'#0F172A' }}>Configure Pivot</h3>
              <div style={{ display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:14 }}>
                {[{label:'Slice by',key:'dimension',options:DIMENSIONS},{label:'Measure',key:'metric',options:METRICS},{label:'Chart Type',key:'chartType',options:CHART_TYPES},{label:'Date Range',key:'dateRange',options:['Last 30 days','Last 90 days','Last 12 months','All time']}].map(field => (
                  <div key={field.key}><label style={{ fontSize:11, fontWeight:600, color:'#64748B', display:'block', marginBottom:6 }}>{field.label}</label><select value={(pivot as any)[field.key]} onChange={e => setPivot(p => ({ ...p,[field.key]:e.target.value }))} style={{ width:'100%', padding:'8px 10px', border:'1px solid #EDE9FE', borderRadius:8, fontSize:13, color:'#0F172A', background:'white', outline:'none' }}>{field.options.map(o => <option key={o} value={o}>{o}</option>)}</select></div>
                ))}
              </div>
              <div style={{ display:'flex', gap:8, marginTop:16 }}>
                <input value={pivot.name} onChange={e => setPivot(p => ({ ...p,name:e.target.value }))} placeholder="Template name" style={{ flex:1, padding:'8px 12px', border:'1px solid #EDE9FE', borderRadius:8, fontSize:13, outline:'none' }}/>
                <button onClick={() => { if(pivot.name) setSavedTemplates(t => [...t,{ ...pivot }]); }} style={{ display:'flex', alignItems:'center', gap:6, padding:'8px 14px', borderRadius:8, background:'#F5F4FF', border:'1px solid #EDE9FE', fontSize:13, color:'#7C3AED', fontWeight:500, cursor:'pointer' }}><Save size={13}/> Save</button>
              </div>
            </div>
            <div className="card" style={{ padding:'24px' }}>
              <h3 style={{ fontSize:14, fontWeight:700, marginBottom:16, color:'#0F172A' }}>{pivot.metric} by {pivot.dimension}</h3>
              {pivot.chartType==='Pie Chart'?(
                <ResponsiveContainer width="100%" height={240}><PieChart><Pie data={pivotData} dataKey="value" cx="50%" cy="50%" outerRadius={100} label={({name}) => name}>{pivotData.map((_,i) => <Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v:any) => formatCurrency(v)}/></PieChart></ResponsiveContainer>
              ):(
                <ResponsiveContainer width="100%" height={240}><BarChart data={pivotData}><CartesianGrid strokeDasharray="3 3" stroke="#F1F0FF"/><XAxis dataKey="name" tick={{ fontSize:11 }}/><YAxis tickFormatter={v=>`$${(v/1000).toFixed(0)}K`} tick={{ fontSize:11 }}/><Tooltip formatter={(v:any) => formatCurrency(v)}/><Bar dataKey="value" fill="#7C3AED" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>
              )}
            </div>
          </div>
        )}
        {tab==='query' && (
          <div className="card" style={{ padding:'32px' }}>
            <div style={{ textAlign:'center', marginBottom:28 }}><div style={{ fontSize:32, marginBottom:8 }}>🔍</div><h3 style={{ fontSize:16, fontWeight:700, color:'#0F172A', marginBottom:6 }}>Natural Language Query Builder</h3><p style={{ fontSize:13, color:'#64748B' }}>Type a question in plain English and Traivio AI will build the report for you</p></div>
            <div style={{ display:'flex', gap:8, maxWidth:600, margin:'0 auto' }}>
              <input value={nlQuery} onChange={e => setNlQuery(e.target.value)} placeholder="e.g. Show me top 10 highest spend travelers last quarter..." style={{ flex:1, padding:'12px 16px', border:'1px solid #EDE9FE', borderRadius:10, fontSize:14, color:'#0F172A', outline:'none' }}/>
              <button style={{ padding:'12px 20px', borderRadius:10, background:'linear-gradient(135deg,#7C3AED,#8B5CF6)', border:'none', color:'white', fontSize:13, fontWeight:600, cursor:'pointer', display:'flex', alignItems:'center', gap:6 }}><Play size={14}/> Run</button>
            </div>
            <div style={{ marginTop:24 }}>
              <div style={{ fontSize:11, fontWeight:600, color:'#94A3B8', marginBottom:12, textAlign:'center' }}>EXAMPLE QUERIES</div>
              <div style={{ display:'flex', flexWrap:'wrap', gap:8, justifyContent:'center' }}>
                {['Which travelers exceeded their policy limit last month?','Show flights booked under 7 days advance by department','Compare Q1 vs Q2 spend by category','Top 5 most expensive routes this year'].map((q,i) => (<button key={i} onClick={() => setNlQuery(q)} style={{ padding:'6px 14px', borderRadius:999, background:'white', border:'1px solid #EDE9FE', fontSize:12, color:'#475569', cursor:'pointer' }}>{q}</button>))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}